---
framework: jest
blacklist:
  - 'src/load.spec.ts##.load##'
postMerge:
  pattern:
    - './src/**/*.spec.ts'
  strategy:
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - './src/**/*.spec.ts'
preRun:
  - npm ci
postRun:
  - node --version
version: 2.0
